/* This is global configuration file for some properties */
MedicalPictures.config(function($translateProvider) {
  $translateProvider.translations('en', {
    'LOGIN_VIEW_HEAD_NAME': 'MedicalPictures Login View',
    'ADMIN_VIEW_HEAD_NAME': 'MedicalPictures Admin View',
    'DOCTOR_VIEW_HEAD_NAME': 'MedicalPictures Doctor View',
    'PATIENT_VIEW_HEAD_NAME': 'MedicalPictures Patient View',
    'SETTINGS_VIEW_HEAD_NAME': 'MedicalPictures Settings View',
    'USERNAME': 'Username',
    'PASSWORD': 'Password',
    'LOG_IN': 'Login',
    'PROVIDE_CREDENTIALS': 'Provide your credentials',
    'INCORRECT_EMAIL': 'Given username (e-mail address) is incorrect',
    'PASSWORD_TOO_SHORT': 'Password is too short!',
    'PASSWORD_TOO_LONG': 'Password is too long!',
    'MENU': 'Menu',
    'SETTINGS': 'Settings',
    'LOGOUT': 'Logout',
    'MANAGE_USERS': 'Manage users',
    'MANAGE_BODY_PARTS': 'Manage body parts',
    'MANAGE_PICTURE_TYPES': 'Manage pictures types',
    'ADD_NEW_USER': 'Add new user',
    'DELETE_USER': 'Delete user',
    'MARK_ALL': 'Mark all',
    'UNMARK_ALL': 'Unmark all',
    'ACCOUNT_TYPE': 'Account type',
    'BACK': 'Go back',
    'CHANGE_YOUR_SETTINGS': 'Change your settings',
    'NAME': 'Name',
    'SURNAME': 'Surname',
    'YOUR_USERNAME': 'Your username',
    'YOUR_NAME': 'Your name',
    'YOUR_SURNAME': 'Your surname',
    'YOUR_PASSWORD': 'Your password',
    'USER_ALREADY_LOGGED_OUTSIDE': 'Given username is already logged somewhere!',
    'USER_ALREADY_LOGGED_LOCALLY': 'Hey you are already logged! Click here to go to the main page!',
    'AUTHENTICATION_FAILED': 'Authentication failed for given credentials.',
    'LOGGED_AS': 'Logged as: ',
    'USERNAME_NAME': 'Username',
    'AGE': 'Age',
    'ADDING_NEW_USER': 'Adding new user',
    'ADD_USER': 'Add user',
    'USER_ADDED_SUCCESSFULLY': "User added successfully!",
    'USER_ADDING_FAILED': "User adding failed! User already exists.",
    'INTERNAL_PROBLEM_OCCURRED': 'Internal problem occurred...!',
    'EDIT': 'Edit',
    'CHECK': 'Check',
    'MODIFY_USER': 'Modify existing user',
    'UPDATE_USER': 'Update user',
    'RESET_PASSWORD': 'Reset password',
    'USER_EDITED_SUCCESSFULLY': 'User has been updated successfully.',
    'PICTURE_TYPES': 'Picture types',
    'PICTURE_TYPE': 'Picture type',
    'ADD_NEW_BODY_PART': 'Add new body part',
    'ADD_NEW_PICTURE_TYPE': 'Add new picture type',
    'ADD': 'Add',
    'PICTURE_TYPE_ADDED_SUCCESSFULLY': 'Picture type has been added successfully!',
    'PICTURE_TYPE_ADDING_FAILED': 'Picture type adding failed...',
    'BODY_PART_ADDED_SUCCESSFULLY': 'Body part has been added successfully!',
    'BODY_PART_ADDING_FAILED': 'Body part adding failed...',
    'BODY_PARTS': 'Body parts',
    'BODY_PART': 'Body part',
    'TECHNICIAN_VIEW_HEAD_NAME': 'MedicalPictures Techician VIew',
    'MANAGE_PICTURES': 'Manage pictures',
    'ADD_NEW_PICTURES': 'Add pictures',
    'DELETE_PICTURES': 'Delete pictures',
    'DROP_PICTURES_HERE': 'Drop picture here',
    'ALL_PICTURES_UPLOADED': 'All pictures have been sent to the server!',
    'ONLY_PICTURES_CAN_BE_UPLOADED': 'Cannot upload. Only pictures can be uploaded!',
    'NO_PATIENT_SELECTED_FOR_FILE': 'There is no patient selected whose picture is uploaded!',
    'NO_BODY_PART_SELECTED_FOR_FILE': 'There is no body which the picture describes!',
    'NO_PICTURE_TYPE_SELECTED_FOR_FILE': 'There is no picture type selected for the picture!',
    'SPECIALIZATION': 'Specialization',
    'PICTURES_LIST': 'Pictures list',
    'PICTURES_LIST_IS_EMPTY': 'There are no found pictures in the system.',
    'CAPTURE_DATE': 'Capture date',
    'TECHNICIAN': 'Technician',
    'PATIENT': 'Patient',
    'REMOVE': 'Remove',
    'SAVE': 'Save',
    'ADD_TO_DB_FAILED': 'Updating or adding item failed. Internal error.',
    'SUCCESSFULLY_EDITED_PICTURE': 'Successfully updated picture!',
    'PICTURE_NAME': 'Picture name',
    'ACTIONS': 'Actions',
    'NO_PATIENTS_FOUND': 'There are not any patients!',
    'PATIENT_PICTURES': 'Patient\'s pictures',
    'DEFINED_PICTURE_DESCRIPTION': 'Defined picture description',
    'PICTURE_THUMBNAIL': 'Picture thumbnail',
    'PATIENT_NAME': 'Patient\'s name',
    'PATIENT_SURNAME': 'Patient\'s surname',
    'PATIENT_USERNAME': 'Patient\'s username',
    'TECHNICIAN_NAME': 'Technician\'s name',
    'TECHNICIAN_SURNAME': 'Technician\'s surname',
    'TECHNICIAN_USERNAME': 'Technician\'s username',
    'CAPTURE_DATE': 'Capture date',
    'PATIENT_AGE': 'Patient\'s age',
    'PICTURE_DESCRIPTION': 'Picture\'s description',
    'REMOVE_DEFINED_PICTURE_DESCRIPTION': 'Remove defined picture description',
    'SAVE_DESCRIPTION': 'Save description',
    'MANAGE_DIAGNOSIS': 'Manage diagnosis',
    'BROWSE_PICTURES_AND_DIAGNOSIS': 'Browse pictures and diagnosis',
    'DOCTOR': 'Doctor\'s diagnosis',
    'DIAGNOSIS_AUTHOR': 'Diagnosi\'s author',
    'NO_PICTURE_DESCRIPTIONS_FOUND': 'No descriptions found for this picture.',
    'YOUR_AGE': 'Your age',
    'CHANGE_PASSWORD': 'Change your password',
    'NEW_PASSWORD': 'New password',
    'NEW_PASSWORD_AGAIN': 'Ensure new password',
    'CHANGE_MY_PASSWORD': 'Change my password',
    'PASSWORDS_ARE_DIFFERENT': 'Passwords are different',
    'INPUT_JSON_PARSE_PROBLEM': 'Ups! Something went wrong with parsing input from client',
    'USERS_SUCCESSFULY_REMOVED':'Deletion succeed!',
    'NO_USERS_TO_REMOVE_SELECTED':'There are no selected users to delete!',
    'BODY_PART_IS_INCORRECT':'Given description of the body part is incorrect!',
    'PICTURE_TYPE_IS_INCORRECT':'Given picture type is incorrect!',
    'BODY_PART_TOO_LONG':'Body part description too long!',
    'PICTURE_TYPE_TOO_LONG':'Picture type is too long!',
    'USERNAME_TOO_LONG':'Username is too long!',
    'SUCCESSFULLY_REMOVED_PICTURE':'Deletion succeed!',
    'SETTINGS_VIEW_HEAD_NAME':'User settings view',
    'MANAGE_YOUR_SETTINGS':'Manage your settings',
    'APPLICATION_LANGUAGE':'Application\'s language',
    'SAVE_CHANGES':'Save changes',
    'SOME_OF_THE_VALUES_ARE_INCORRECT':'There are mistakes in paramaters.Check your configuration!',
    'MANAGE_DEFINFED_PICTURE_DESCRIPTIONS':'Manage defined picture descriptions',
    'DEFINED_DESCRIPTION_NAME':'Defined description name',
    'DEFINED_PICTURE_DESCRIPTION_TOO_LONG':'Defined picture description is too long!',
    'DEFINED_PICTURE_DESCRIPTION_NAME_TOO_LONG':'Defined picture description name is too long',
    'DEFINED_PICTURE_DESCRIPTIONS':'Defined picture descriptions',
    'DEFINED_PICTURE_DESCRIPTION_IS_INCORRECT':'Defined picture description is incorrect!Correct it ',
    'OBJECT_DUPLICATION_ERROR':'Can\'t add object because it already exists in database!',
  });
  $translateProvider.translations('pl', {
    'LOGIN_VIEW_HEAD_NAME': 'MedicalPictures Panel Logowania',
    'ADMIN_VIEW_HEAD_NAME': 'MedicalPictures Panel Administratora',
    'DOCTOR_VIEW_HEAD_NAME': 'MedicalPictures Panel Doktora',
    'PATIENT_VIEW_HEAD_NAME': 'MedicalPictures Panel Pacjenta',
    'SETTINGS_VIEW_HEAD_NAME': 'MedicalPictures Panel Ustawień',
    'USERNAME': 'Użytkownik',
    'LOG_IN': 'Zaloguj',
    'PASSWORD': 'Hasło',
    'PROVIDE_CREDENTIALS': 'Podaj swój login oraz hasło',
    'INCORRECT_EMAIL': 'Podana nazwa użytkownika (adres e-mail) jest niepoprawny',
    'PASSWORD_TOO_SHORT': 'Hasło jest za krótkie!',
    'PASSWORD_TOO_LONG': 'Hasło jest za długie!',
    'MENU': 'Menu',
    'SETTINGS': 'Ustawienia',
    'LOGOUT': 'Wyloguj',
    'MANAGE_USERS': 'Zarządzaj użytkownikami',
    'MANAGE_BODY_PARTS': 'Zarządzaj częściami ciała',
    'MANAGE_PICTURE_TYPES': 'Zarządzaj typami zdjęć',
    'ADD_NEW_USER': 'Dodaj nowego użytkownika',
    'DELETE_USER': 'Usuń użytkownika',
    'MARK_ALL': 'Zaznacz wszystkich',
    'UNMARK_ALL': 'Odznacz wszytkich',
    'ACCOUNT_TYPE': 'Typ konta',
    'BACK': 'Powrót',
    'CHANGE_YOUR_SETTINGS': 'Zmień swoje ustawienia',
    'NAME': 'Imię',
    'SURNAME': 'Nazwisko',
    'YOUR_USERNAME': 'Twoja nazwa użytkownika',
    'YOUR_NAME': 'Twoje imię',
    'YOUR_SURNAME': 'Twoje nazwisko',
    'YOUR_PASSWORD': 'Twoje hasło',
    'USER_ALREADY_LOGGED_OUTSIDE': 'Podany użytkownik jest już zalogowany gdzieś indziej!',
    'USER_ALREADY_LOGGED_LOCALLY': 'Hej, jesteś już zalogowany! Kliknij tu, aby przejść do okna głównego.',
    'AUTHENTICATION_FAILED': 'Logowanie nie powiodło się.',
    'LOGGED_AS': 'Zalogowany jako: ',
    'USERNAME_NAME': 'Nazwa użytkownika',
    'AGE': 'Wiek',
    'ADDING_NEW_USER': 'Dodawanie nowego użytkownika',
    'ADD_USER': 'Dodaj użytkownika',
    'USER_ADDED_SUCCESSFULLY': "Użytkownik dodany!",
    'USER_ADDING_FAILED': "Nie udało się dodać użytkownika. Użytkownik już istnieje!",
    'INTERNAL_PROBLEM_OCCURRED': 'Wystąpił problem w systemie!',
    'EDIT': 'Edytuj',
    'CHECK': 'Zaznacz',
    'MODIFY_USER': 'Edytuj istniejącego użytkownika',
    'UPDATE_USER': 'Aktualizuj użytkownika',
    'RESET_PASSWORD': 'Resetuj hasło',
    'USER_EDITED_SUCCESSFULLY': 'Dane użytkownika zostały zaktualizowane.',
    'PICTURE_TYPES': 'Typy zdjęć',
    'PICTURE_TYPE': 'Typ zdjęcia',
    'ADD_NEW_BODY_PART': 'Dodaj część ciała',
    'ADD_NEW_PICTURE_TYPE': 'Dodaj nowy typ zdjęć',
    'ADD': 'Dodaj',
    'PICTURE_TYPE_ADDED_SUCCESSFULLY': 'Typ zdjęcia został dodany!',
    'PICTURE_TYPE_ADDING_FAILED': 'Typ zdjęcia nie został dodany...',
    'BODY_PART_ADDED_SUCCESSFULLY': 'Część ciała została dodana!',
    'BODY_PART_ADDING_FAILED': 'Dodanie części ciała nie powiodło się...',
    'BODY_PARTS': 'Części ciała',
    'BODY_PART': 'Część ciała',
    'TECHNICIAN_VIEW_HEAD_NAME': 'MedicalPictures Panel Technika',
    'MANAGE_PICTURES': 'Zarządzaj zdjęciami',
    'ADD_NEW_PICTURES': 'Dodaj zdjęcia',
    'DELETE_PICTURES': 'Usuń zdjęcia',
    'DROP_PICTURES_HERE': 'Przeciągnij zdjęcia tutaj',
    'ALL_PICTURES_UPLOADED': 'Wszystkie zdjęcia zostały wysłane do serwera!',
    'ONLY_PICTURES_CAN_BE_UPLOADED': 'Nie można załadować. Dozwolne są tylko obrazy/zdjęcia!',
    'NO_PATIENT_SELECTED_FOR_FILE': 'Nie wybrano pacjenta, dla którego to zdjęcie jest ładowane!',
    'NO_BODY_PART_SELECTED_FOR_FILE': 'Nie wybrano części ciała dla podanego zdjęcia!',
    'NO_PICTURE_TYPE_SELECTED_FOR_FILE': 'Nie wybrano typu zdjęcia dla podanego obrazu!',
    'SPECIALIZATION': 'Specjalizacja',
    'PICTURES_LIST': 'Lista zdjęć',
    'PICTURES_LIST_IS_EMPTY': 'W systemie nie ma żadnych zdjęć.',
    'CAPTURE_DATE': 'Data wykonania',
    'TECHNICIAN': 'Technik',
    'PATIENT': 'Pacjent',
    'REMOVE': 'Usuń',
    'SAVE': 'Zapisz',
    'ADD_TO_DB_FAILED': 'Aktualizowanie bądź dodawanie nie udane. Błąd wewnętrzny.',
    'SUCCESSFULLY_EDITED_PICTURE': 'Zaktualizowano zdjęcie!',
    'PICTURE_NAME': 'Zdjęcie',
    'ACTIONS': 'Akcje',
    'NO_PATIENTS_FOUND': 'Brak jakichkolwiek pacjentów!',
    'PATIENT_PICTURES': 'Zdjęcia pacjenta',
    'DEFINED_PICTURE_DESCRIPTION': 'Zdefiniowany opis zdjęcia',
    'PICTURE_THUMBNAIL': 'Miniatura zdjęcia',
    'PATIENT_NAME': 'Imię pacjenta',
    'PATIENT_SURNAME': 'Nazwisko pacjenta',
    'PATIENT_USERNAME': 'Nazwa użytkownika pacjenta',
    'TECHNICIAN_NAME': 'Imię technika',
    'TECHNICIAN_SURNAME': 'Nazwisko technika',
    'TECHNICIAN_USERNAME': 'Nazwa użytkownika technika',
    'CAPTURE_DATE': 'Data wykonania',
    'PATIENT_AGE': 'Wiek pacjenta',
    'PICTURE_DESCRIPTION': 'Opis zdjęcia',
    'REMOVE_DEFINED_PICTURE_DESCRIPTION': 'Usuń zdefiniowany opis zdjęcia',
    'SAVE_DESCRIPTION': 'Zapisz opis',
    'MANAGE_DIAGNOSIS': 'Zarządzaj diagnozami',
    'BROWSE_PICTURES_AND_DIAGNOSIS': 'Przeglądaj zdjęcia i diagnozy',
    'DOCTOR_DIAGNOSIS': 'Diagnoza doktora',
    'DIAGNOSIS_AUTHOR': 'Autor diagnozy',
    'NO_PICTURE_DESCRIPTIONS_FOUND': 'Brak jakichkolwiek diagnoz dla tego zdjęcia.',
    'YOUR_AGE': 'Twój wiek',
    'CHANGE_PASSWORD': 'Zmień swoje hasło',
    'NEW_PASSWORD': 'Nowe hasło',
    'NEW_PASSWORD_AGAIN': 'Potwierdź nowe hasło',
    'CHANGE_MY_PASSWORD': 'Zmień moje hasło',
    'PASSWORDS_ARE_DIFFERENT': 'Hasła różnią się...',
    'INPUT_JSON_PARSE_PROBLEM': 'Ups! Pojawił się problem z parsowaniem zapytania przez serwer.',
    'USERS_SUCCESSFULY_REMOVED':'Usuwanie zakończone sukcesem!',
    'NO_USERS_TO_REMOVE_SELECTED':'Nie wybrano żadnych użytkowników do usunięcia!',
    'BODY_PART_IS_INCORRECT':'Wprowadzony opis części ciała jest niewłaściwy!',
    'PICTURE_TYPE_IS_INCORRECT':'Podany typ zdjęcia jest nieprawidłowy!',
    'BODY_PART_TOO_LONG':'Opis części ciała jest za długi!',
    'PICTURE_TYPE_TOO_LONG':'Typ zdjęcia jest za długi!',
    'USERNAME_TOO_LONG':'Nazwa użytkownika jest za długa!',
    'SUCCESSFULLY_REMOVED_PICTURE':'Usuwanie zakończone sukcesem',
    'SETTINGS_VIEW_HEAD_NAME':'Panel ustawień użytkownika',
    'MANAGE_YOUR_SETTINGS':'Zarządzaj swoimi ustawieniami',
    'APPLICATION_LANGUAGE':'Język aplikacji',
    'SAVE_CHANGES':'Zapisz zmiany',
    'SOME_OF_THE_VALUES_ARE_INCORRECT':'Wystąpiły błędy w podanych parametrach. Sprawdź konfigurację!',
    'MANAGE_DEFINFED_PICTURE_DESCRIPTIONS':'Zarządzaj zdefiniowanymi opisami zdjęć',
    'DEFINED_DESCRIPTION_NAME':'Nazwa zdefiniowanego opisu',
    'DEFINED_PICTURE_DESCRIPTION_TOO_LONG':'Zdefiniowany opis zdjęcia jest za długi!',
    'DEFINED_PICTURE_DESCRIPTION_NAME_TOO_LONG':'Nazwa zdefiniowanego opisu zdjęć jest za długa!',
    'DEFINED_PICTURE_DESCRIPTIONS':'Zdefiniowane opisy zdjęć',
    'DEFINED_PICTURE_DESCRIPTION_IS_INCORRECT':'Zdefniowany opis zdjęcia jest niepoprawny. Popraw go - nazwę lub opis!',
    'OBJECT_DUPLICATION_ERROR':'Nie można dodać obiektu, poniważ już istnieje w bazie danych!',
  });
  $translateProvider.preferredLanguage('pl');
});
